sonar.projectKey=mavenproject1
sonar.projectName=mavenproject1
sonar.projectVersion=1.0

sonar.sources=src/main/java

sonar.tests=src/test/java

sonar.sourceEncoding=UTF-8

sonar.host.url=http://localhost:9000

sonar.token=squ_13671772500e912265a59827fba88faaa713a262